deploymentMode: SingleBinary

loki:
  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  limits_config:
    retention_period: 168h

  compactor:
    retention_enabled: true
    delete_request_store: filesystem

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi

chunksCache:
  enabled: false

resultsCache:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false

minio:
  enabled: false

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0