apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nexus
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/rodrigomsr2/k8s-gitops
        revision: main
        directories:
          - path: apps/nexus/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rodrigomsr2/k8s-gitops
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: nexus
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
